version: "3.8"
volumes:
  dynamodb_data:
services:
  dynamodb-local:
    container_name: dynamodb-local
    image: "amazon/dynamodb-local:latest"
    command: "-jar DynamoDBLocal.jar -sharedDb -optimizeDbBeforeStartup -dbPath ./data"
    volumes:
      - "./docker/dynamodb:/home/dynamodblocal/data"
    working_dir: /home/dynamodblocal
    ports:
      - "8000:8000"
    environment:
      AWS_ACCESS_KEY_ID: 'dummy-key'
      AWS_SECRET_ACCESS_KEY: 'dummy-secret'
      REGION: 'US_EAST_1'